/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/conditions/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conditions
         * @description Return the freshest conditions snapshot for ``station_id``.
         */
        get: operations["get_conditions_api_v1_conditions__station_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query
         * @description Stream a recommendation for one natural-language fishing query.
         *
         *     Returns ``EventSourceResponse`` whose generator yields events in the
         *     locked sequence (in-scope happy path):
         *
         *         progress(planner)  ← emitted by the ROUTE at stream open (W-4)
         *         progress(planner)  ← emitted by the runtime after planner update
         *         progress(data_fetcher)
         *         partial_conditions
         *         progress(rag_retriever)
         *         progress(synthesizer)
         *         recommendation
         */
        post: operations["query_api_v1_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Spots
         * @description Return scored spots within bbox.
         *
         *     ``hours_ahead`` reserved for future forecast use; Phase 3 returns current
         *     scores only (forecast support is v1.x).
         */
        get: operations["list_spots_api_v1_spots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ConditionsResponse
         * @description Full ``/conditions/{station_id}`` response payload.
         */
        ConditionsResponse: {
            /** Station Id */
            station_id: string;
            /** Station Name */
            station_name: string;
            /**
             * Observed At
             * Format: date-time
             * @description CAGG bucket start time
             */
            observed_at: string;
            /** Data Age Seconds */
            data_age_seconds: number;
            tidal: components["schemas"]["TidalBlock"];
            weather: components["schemas"]["WeatherBlock"];
            solunar: components["schemas"]["SolunarBlock"];
            /** Sunrise */
            sunrise?: string | null;
            /** Sunset */
            sunset?: string | null;
        };
        /**
         * ErrorEnvelope
         * @description Canonical error body for 503 / 404 responses.
         */
        ErrorEnvelope: {
            /**
             * Code
             * @enum {string}
             */
            code: "conditions_stale" | "conditions_unavailable" | "station_not_found";
            /** Message */
            message: string;
            /** Latest Bucket */
            latest_bucket?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LocationHint
         * @description Optional spatial context for spot resolution (D-05).
         */
        LocationHint: {
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Spot Name */
            spot_name?: string | null;
        };
        /**
         * QueryBody
         * @description User query body. SEC-06 bound: max_length=500 on the natural-language query.
         */
        QueryBody: {
            /** Query */
            query: string;
            location_hint?: components["schemas"]["LocationHint"] | null;
        };
        /**
         * SolunarBlock
         * @description Solunar block — computed values. Fields are Optional because the
         *     solunar beat task may not have run yet for a given station; see WR-02.
         *     Silent ``0.0`` substitution (``None or 0.0``) was removed — a genuine
         *     new-moon reading of 0.0 is distinguishable from a missing row at the
         *     cost of a nullable contract.
         */
        SolunarBlock: {
            /** Moon Phase */
            moon_phase?: number | null;
            /** Illumination */
            illumination?: number | null;
            /** Lunar Day */
            lunar_day?: number | null;
            /** Next Major Start */
            next_major_start?: string | null;
            /** Next Major End */
            next_major_end?: string | null;
            /** Next Minor Start */
            next_minor_start?: string | null;
            /** Next Minor End */
            next_minor_end?: string | null;
            /** Quality Score */
            quality_score?: number | null;
        };
        /**
         * SpotScore
         * @description One row of the /api/v1/spots response.
         *
         *     ``score`` / ``confidence`` / ``species`` / ``last_score_time`` /
         *     ``data_age_seconds`` are ``None`` when the spot exists in the bbox but
         *     has no scoring rows (cold spot — Celery scorer hasn't reached it yet).
         */
        SpotScore: {
            /** Spot Id */
            spot_id: number;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Score */
            score?: number | null;
            /** Confidence */
            confidence?: string | null;
            /** Species */
            species?: string | null;
            /** Last Score Time */
            last_score_time?: string | null;
            /** Data Age Seconds */
            data_age_seconds?: number | null;
        };
        /**
         * TidalBlock
         * @description Tidal block — every field optional (sensors may be offline).
         */
        TidalBlock: {
            /** Current Level M */
            current_level_m?: number | null;
            /**
             * Phase
             * @default unknown
             * @enum {string}
             */
            phase: "incoming" | "outgoing" | "slack" | "unknown";
            /** Water Temp C */
            water_temp_c?: number | null;
            /** Next High */
            next_high?: string | null;
            /** Next High Level M */
            next_high_level_m?: number | null;
            /** Next Low */
            next_low?: string | null;
            /** Next Low Level M */
            next_low_level_m?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WeatherBlock
         * @description Weather block — all sensor fields optional.
         */
        WeatherBlock: {
            /** Wind Speed Ms */
            wind_speed_ms?: number | null;
            /** Wind Direction Deg */
            wind_direction_deg?: number | null;
            /** Surface Pressure Hpa */
            surface_pressure_hpa?: number | null;
            /** Pressure Delta 1H */
            pressure_delta_1h?: number | null;
            /** Pressure Delta 3H */
            pressure_delta_3h?: number | null;
            /** Pressure Delta 6H */
            pressure_delta_6h?: number | null;
            /** Pressure Trend Label */
            pressure_trend_label?: ("Rapid Rise" | "Rising" | "Steady" | "Falling" | "Rapid Fall") | null;
            /** Air Temperature C */
            air_temperature_c?: number | null;
            /** Precipitation Prob Pct */
            precipitation_prob_pct?: number | null;
            /** Cloud Cover Pct */
            cloud_cover_pct?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_conditions_api_v1_conditions__station_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionsResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    query_api_v1_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_spots_api_v1_spots_get: {
        parameters: {
            query: {
                /** @description lat1,lon1,lat2,lon2 */
                bbox: string;
                species?: string | null;
                hours_ahead?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotScore"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}

// ─── SSE event payloads (hand-mirrored from backend/agent/sse_protocol.py) ───
// The OpenAPI spec describes only HTTP routes; SSE event payloads are not
// surfaced by FastAPI for StreamingResponse routes. These types MUST be kept
// in sync with backend/agent/sse_protocol.py manually. See gen-api-types.ts.

export type SSEEventType =
  | "progress"
  | "partial_conditions"
  | "recommendation"
  | "error";

export type SSEErrorCode =
  | "rate_limited"
  | "planner_timeout"
  | "planner_out_of_scope"
  | "llm_unavailable"
  | "internal";

export type ProgressStage =
  | "planner"
  | "data_fetcher"
  | "rag_retriever"
  | "synthesizer";

export type ConfidenceLabel = "High" | "Moderate" | "Low";

export interface ProgressPayload {
  stage: ProgressStage;
}

export interface PartialConditionsPayload {
  spot_id: number | null;
  spot_name: string | null;
  conditions: Record<string, unknown> | null;
  ml_score: number | null;
  shap_top3: string[] | null;
  data_age_seconds: number | null;
  conditions_stale: boolean;
}

export interface CitationOut {
  source: string;
  date: string | null;
  chunk_id: string | null;
  source_url: string | null;
}

export interface RecommendationPayload {
  recommendation_text: string;
  citations: CitationOut[];
  confidence_label: ConfidenceLabel;
  retrieval_ok: boolean;
  ml_score_available: boolean;
  conditions_stale: boolean;
  data_age_seconds: number | null;
  spot_id: number | null;
  spot_name: string | null;
  ml_score: number | null;
  shap_top3: string[] | null;
  rag_latency_ms: number | null;
  species_canonical: string | null;
  time_window_label: string | null;
}

export interface ErrorPayload {
  code: SSEErrorCode;
  message: string;
  partial_state: Record<string, unknown> | null;
}
